# Generated by Django 3.1.8 on 2021-09-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=6)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date_registered', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user')),
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('isAtLevel1', models.BooleanField(default=True)),
                ('isAtLevel2', models.BooleanField(default=False)),
                ('isAtLevel3', models.BooleanField(default=False)),
                ('isAtLevel4', models.BooleanField(default=False)),
                ('isAtLevel5', models.BooleanField(default=False)),
                ('isAtLevel6', models.BooleanField(default=False)),
                ('lastLogin', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Child',
            },
            bases=('user.user',),
        ),
    ]
