# Generated by Django 3.1.1 on 2021-09-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='isAtLevel6',
        ),
    ]
